// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxnvqbkbmrniayiumbro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4bnZxYmtibXJuaWF5aXVtYnJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDAxNzcsImV4cCI6MjA2MTQxNjE3N30.uQxQnZ3WTADF5HUvW7PI1NjsZoClJ2I1sjO1Zh-SnDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);